// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATjApb2GyKZvraQEohOZ--FCBxQPU70yc',
    appId: '1:227171072442:web:157572d9d45c44e6118583',
    messagingSenderId: '227171072442',
    projectId: 'flutter-firebase-4e713',
    authDomain: 'flutter-firebase-4e713.firebaseapp.com',
    storageBucket: 'flutter-firebase-4e713.appspot.com',
    measurementId: 'G-K3N358N968',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbM0sFu3fEaYnBB63xGODHo3TkyNtn4s',
    appId: '1:227171072442:android:8a516985f046df30118583',
    messagingSenderId: '227171072442',
    projectId: 'flutter-firebase-4e713',
    storageBucket: 'flutter-firebase-4e713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRj_8C8ya_x0xsmHu_bXaPt3L0YBqmOM',
    appId: '1:227171072442:ios:827a1edf82d23f93118583',
    messagingSenderId: '227171072442',
    projectId: 'flutter-firebase-4e713',
    storageBucket: 'flutter-firebase-4e713.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRj_8C8ya_x0xsmHu_bXaPt3L0YBqmOM',
    appId: '1:227171072442:ios:827a1edf82d23f93118583',
    messagingSenderId: '227171072442',
    projectId: 'flutter-firebase-4e713',
    storageBucket: 'flutter-firebase-4e713.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATjApb2GyKZvraQEohOZ--FCBxQPU70yc',
    appId: '1:227171072442:web:c6884165029f472c118583',
    messagingSenderId: '227171072442',
    projectId: 'flutter-firebase-4e713',
    authDomain: 'flutter-firebase-4e713.firebaseapp.com',
    storageBucket: 'flutter-firebase-4e713.appspot.com',
    measurementId: 'G-WXBTTPK8MW',
  );
}
